traits_list_html = {
    1:["a) Skin color","Light beige",1],
    2:["a) Skin color","Beige",1],
    3:["a) Skin color","Tanned beige",1],
    4:["a) Skin color","Half-breed ~ Light",1],
    5:["a) Skin color","Half-breed ~ Darker",1],
    6:["a) Skin color","Black",1],
    10001:["l) On mouth","None",10],
    7:["l) On mouth","Cigarette",10],
    8:["l) On mouth","Marijuana joint",10],
    9:["b) Face","Bored",1],
    10:["b) Face","Greedy",1],
    11:["b) Face","Upset",1],
    10002:["c) Haircut","None",2],
    12:["c) Haircut","Men haircut 1",2],
    13:["c) Haircut","Men haircut 2",2],
    14:["c) Haircut","Men haircut 3",2],
    15:["c) Haircut","Men haircut 4",2],
    16:["c) Haircut","Men haircut 5",2],
    17:["c) Haircut","Men haircut 6",2],
    18:["c) Haircut","Women haircut 1",2],
    19:["c) Haircut","Women haircut 2",2],
    20:["c) Haircut","Women haircut 3",2],
    21:["c) Haircut","Women haircut 4",2],
    22:["c) Haircut","Women haircut 5",2],
    23:["c) Haircut","Women haircut 6",2],
    10003:["e) Beard","None",4],
    24:['e) Beard', 'Beardcut 1',9],
    25:['e) Beard', 'Beardcut 2',9],
    26:['e) Beard', 'Beardcut 3',9],
    27:['e) Beard', 'Beardcut 4',9],
    28:['e) Beard', 'Beardcut 5',9],
    29:['e) Beard', 'Beardcut 6',9],
    30:['d) Hair color', 'Hair Color 1',2],
    31:['d) Hair color', 'Hair Color 2',2],
    32:['d) Hair color', 'Hair Color 3',2],
    33:['d) Hair color', 'Hair Color 4',2],
    34:['d) Hair color', 'Hair Color 5',2],
    35:['d) Hair color', 'Hair Color 6',2],
    36:['d) Hair color', 'Hair Color 7',2],
    37:['d) Hair color', 'Hair Color 8',2],
    38:['f) Beard color', 'Beard Color 1',9],
    39:['f) Beard color', 'Beard Color 2',9],
    40:['f) Beard color', 'Beard Color 3',9],
    41:['f) Beard color', 'Beard Color 4',9],
    42:['f) Beard color', 'Beard Color 5',9],
    43:['f) Beard color', 'Beard Color 6',9],
    44:['f) Beard color', 'Beard Color 7',9],
    45:['f) Beard color', 'Beard Color 8',9],
    10004:['g) Top clothing', 'None',3],
    46:['g) Top clothing', 'Jacket ~ Black',3],
    47:['g) Top clothing', 'Jacket ~ Marine blue',3],
    48:['g) Top clothing', 'Jacket ~ Grey',3],
    10005:['h) Jacket Elements', 'None',5],
    49:['h) Jacket Elements', 'Tie 1',5],
    50:['h) Jacket Elements', 'Tie 2',5],
    51:['h) Jacket Elements', 'Tie 3',5],
    52:['h) Jacket Elements', 'Tiebow 1',5],
    53:['h) Jacket Elements', 'Tiebow 2',5],
    54:['h) Jacket Elements', 'Tiebow 3',5],
    10006:['j) Hat', 'None',4],
    55:['j) Hat', 'Dior hat 1',4],
    56:['j) Hat', 'Dior hat 2',4],
    57:['j) Hat', 'Dior hat 3',4],
    58:['g) Top clothing', 'Dior Jacket 1',3],
    59:['g) Top clothing', 'Dior Jacket 2',3],
    60:['g) Top clothing', 'Gucci Jacket 1',3],
    61:['g) Top clothing', 'Gucci Jacket 2',3],
    62:['g) Top clothing', 'Chemise 1',3],
    63:['g) Top clothing', 'Chemise 2',3],
    64:['g) Top clothing', 'Chemise 3',3],
    65:['g) Top clothing', 'Chemise 4',3],
    66:['g) Top clothing', 'Chemise 5',3],
    67:['g) Top clothing', 'Chemise 6',3],
    68:['g) Top clothing', 'Chemise 7',3],
    69:['g) Top clothing', 'Chemise 8',3],
    70:['g) Top clothing', 'Chemise 9',3],
    71:['g) Top clothing', 'Chemise a',3],
    10007:['i) On jacket pocket', 'None'],
    72:['i) On jacket pocket', 'Cryptocom Ruby card',4],
    73:['i) On jacket pocket', 'Cryptocom Jade Green card',4],
    74:['i) On jacket pocket', 'Cryptocom Royal Indigo card',4],
    75:['i) On jacket pocket', 'Cryptocom Frosted Rose Gold card',4],
    76:['i) On jacket pocket', 'Cryptocom Icy White card',4],
    77:['i) On jacket pocket', 'Cryptocom Obsidian card',4],
    78:['i) On jacket pocket', 'Binance card',4],
    79:['g) Top clothing', 'Tank Top 1',3],
    80:['g) Top clothing', 'Tank Top 2',3],
    81:['g) Top clothing', 'Tank Top 3',3],
    82:['g) Top clothing', 'Tank Top 4',3],
    83:['g) Top clothing', 'Tank Top 5',3],
    84:['g) Top clothing', 'Tank Top 6',3],
    85:['g) Top clothing', 'Tank Top 7',3],
    86:['g) Top clothing', 'Tank Top 8',3],
    87:['g) Top clothing', 'Tank Top 9',3],
    88:['g) Top clothing', 'Tank Top a',3],
    89:['g) Top clothing', 'T-shirt 1',3],
    90:['g) Top clothing', 'T-shirt 2',3],
    91:['g) Top clothing', 'T-shirt 3',3],
    92:['g) Top clothing', 'T-shirt 4',3],
    93:['g) Top clothing', 'T-shirt 5',3],
    94:['g) Top clothing', 'T-shirt 6',3],
    95:['g) Top clothing', 'T-shirt 7',3],
    96:['g) Top clothing', 'T-shirt 8',3],
    97:['g) Top clothing', 'T-shirt 9',3],
    98:['g) Top clothing', 'T-shirt a',3],
    10008:['k) Glasses', 'None',3],
    99:['k) Glasses', 'Design 1',3],
    100:['k) Glasses', 'Design 1 ~ Solar',3],
    101:['k) Glasses', 'Design 2',3],
    102:['k) Glasses', 'Design 2 ~ Solar',3],
    103:['k) Glasses', 'Design 3',3],
    104:['k) Glasses', 'Design 3 ~ Solar',3],
    105:['k) Glasses', 'Design 4',3],
    106:['k) Glasses', 'Design 4 ~ Solar',3],
    107:['k) Glasses', 'Design 5',3],
    108:['k) Glasses', 'Design 5 ~ Solar',3],
    109:['k) Glasses', 'Design 6',3],
    110:['k) Glasses', 'Design 6 ~ Solar',3],
    111:['k) Glasses', 'Design 7',3],
    112:['k) Glasses', 'Design 7 ~ Solar',3],
    113:['k) Glasses', 'Design 8',3],
    114:['k) Glasses', 'Design 8 ~ Solar',3],
    115:['k) Glasses', 'Design 9',3],
    116:['k) Glasses', 'Design 9 ~ Solar',3],
    117:['k) Glasses', 'Design a',3],
    118:['k) Glasses', 'Design a ~ Solar',3],
    119:['j) Hat', 'Cap 1',4],
    120:['j) Hat', 'Cap 2',4],
    121:['j) Hat', 'Cap 3',4],
    122:['j) Hat', 'Cap 4',4],
    123:['j) Hat', 'Cap 5',4],
    10009:['m) Pendants', 'None',6],
    124:['m) Pendants', 'Bitcoin Pendant',6],
    125:['m) Pendants', 'Ethereum Pendant',6],
    126:['m) Pendants', 'Solana Pendant',6],
    10010:['n) Misc', 'None',2],
    127:['n) Misc', 'Airpods ~ White',2],
    128:['n) Misc', 'Airpods ~ Mate black',2],
    129:['l) On mouth', 'Gum bubble ~ Pale rose',10],
    130:['l) On mouth', 'Gum bubble ~ Pale blue',10],
    131:['l) On mouth', 'Gum bubble ~ Pale green',10],
    132:['l) On mouth', 'Gum bubble ~ Pale yellow',10],
}