traits_lst = {
    1:["Skin Color","Light beige"],
    2:["Skin Color","Beige"],
    3:["Skin Color","Tanned beige"],
    4:["Skin Color","Half-breed (Light)"],
    5:["Skin Color","Half-breed (Darker)"],
    6:["Skin Color","Black"],

    7:["Face","Bored"],
    8:["Face","Greedy"],
    9:["Face","Upset"],
    10:["Face","Tongue out"],

    11:["Eyes Color","Blue"],
    12:["Eyes Color","Brown"],
    13:["Eyes Color","Green"],

    14:["Morphology","Skinny"],
    15:["Morphology","Average"],
    16:["Morphology","In Shape"],

    10001:["Haircut","None"],
    17:["Haircut","Men haircut 1"],
    18:["Haircut","Men haircut 2"],
    19:["Haircut","Men haircut 3"],
    20:["Haircut","Men haircut 4"],
    21:["Haircut","Men haircut 5"],
    22:["Haircut","Men haircut 6"],
    23:["Haircut","Women haircut 1"],
    24:["Haircut","Women haircut 2"],
    25:["Haircut","Women haircut 3"],
    26:["Haircut","Women haircut 4"],
    27:["Haircut","Women haircut 5"],
    28:["Haircut","Women haircut 6"],

    29:["Hair Color", "Hair Color 1"],
    30:["Hair Color", "Hair Color 2"],
    31:["Hair Color", "Hair Color 3"],
    32:["Hair Color", "Hair Color 4"],
    33:["Hair Color", "Hair Color 5"],
    34:["Hair Color", "Hair Color 6"],
    35:["Hair Color", "Hair Color 7"],
    36:["Hair Color", "Hair Color 8"],

    10002:["Beardcut","None"],
    37:["Beardcut", "Beardcut 1"],
    38:["Beardcut", "Beardcut 2"],
    39:["Beardcut", "Beardcut 3"],
    40:["Beardcut", "Beardcut 4"],
    41:["Beardcut", "Beardcut 5"],
    42:["Beardcut", "Beardcut 6"],

    43:["Beard Color", "Beard Color 1"],
    44:["Beard Color", "Beard Color 2"],
    45:["Beard Color", "Beard Color 3"],
    46:["Beard Color", "Beard Color 4"],
    47:["Beard Color", "Beard Color 5"],
    48:["Beard Color", "Beard Color 6"],
    49:["Beard Color", "Beard Color 7"],
    50:["Beard Color", "Beard Color 8"],

    10003:["Top clothing", "None"],
    51:["Top clothing", "Jacket (Black)"],
    52:["Top clothing", "Jacket (Marine blue)"],
    53:["Top clothing", "Jacket (Grey)"],
    54:["Top clothing", "Dior Jacket 1"],
    55:["Top clothing", "Dior Jacket 2"],
    56:["Top clothing", "Gucci Jacket 1"],
    57:["Top clothing", "Gucci Jacket 2"],
    58:["Top clothing", "Chemise 1"],
    59:["Top clothing", "Chemise 2"],
    60:["Top clothing", "Chemise 3"],
    61:["Top clothing", "Chemise 4"],
    62:["Top clothing", "Chemise 5"],
    63:["Top clothing", "Chemise 6"],
    64:["Top clothing", "Chemise 7"],
    65:["Top clothing", "Chemise 8"],
    66:["Top clothing", "Chemise 9"],
    67:["Top clothing", "Chemise a"],
    68:["Top clothing", "Bitcoin Tank Top"],
    69:["Top clothing", "Ethereum Tank Top"],
    70:["Top clothing", "Tank Top 1"],
    71:["Top clothing", "Tank Top 2"],
    72:["Top clothing", "Tank Top 3"],
    73:["Top clothing", "Tank Top 4"],
    74:["Top clothing", "Tank Top 5"],
    75:["Top clothing", "Tank Top 6"],
    76:["Top clothing", "Tank Top 7"],
    77:["Top clothing", "Tank Top 8"],
    78:["Top clothing", "Bitcoin T-shirt"],
    79:["Top clothing", "Ethereum T-shirt"],
    80:["Top clothing", "T-shirt 1"],
    81:["Top clothing", "T-shirt 2"],
    82:["Top clothing", "T-shirt 3"],
    83:["Top clothing", "T-shirt 4"],
    84:["Top clothing", "T-shirt 5"],
    85:["Top clothing", "T-shirt 6"],
    86:["Top clothing", "T-shirt 7"],
    87:["Top clothing", "T-shirt 8"],

    10004:["Jacket Elements", "None"],
    88:["Jacket Elements", "Tie 1"],
    89:["Jacket Elements", "Tie 2"],
    90:["Jacket Elements", "Tie 3"],
    91:["Jacket Elements", "Tiebow 1"],
    92:["Jacket Elements", "Tiebow 2"],
    93:["Jacket Elements", "Tiebow 3"],
    
    10005:["On Pocket", "None"],
    94:["On Pocket", "Cryptocom Ruby card"],
    95:["On Pocket", "Cryptocom Jade Green card"],
    96:["On Pocket", "Cryptocom Royal Indigo card"],
    97:["On Pocket", "Cryptocom Frosted Rose Gold card"],
    98:["On Pocket", "Cryptocom Icy White card"],
    99:["On Pocket", "Cryptocom Obsidian card"],
    100:["On Pocket", "Binance card"],

    10006:["Hat", "None"],
    101:["Hat", "Dior hat 1"],
    102:["Hat", "Dior hat 2"],
    103:["Hat", "Dior hat 3"],
    104:["Hat", "Cap 1"],
    105:["Hat", "Cap 2"],
    106:["Hat", "Cap 3"],
    107:["Hat", "Cap 4"],
    108:["Hat", "Cap 5"],
    109:["Hat", "Straw hat (Pink)"],
    110:["Hat", "Straw hat (Blue)"],
    
    10007:["Glasses", "None"],
    111:["Glasses", "Design 1"],
    112:["Glasses", "Design 1 (Solar)"],
    113:["Glasses", "Design 1 (Solar over head)"],
    114:["Glasses", "Design 2"],
    115:["Glasses", "Design 2 (Solar)"],
    116:["Glasses", "Design 3 (Solar over head)"],
    117:["Glasses", "Design 3"],
    118:["Glasses", "Design 3 (Solar)"],
    119:["Glasses", "Design 3 (Solar over head)"],
    120:["Glasses", "Design 4"],
    121:["Glasses", "Design 4 (Solar)"],
    122:["Glasses", "Design 4 (Solar over head)"],
    123:["Glasses", "Design 5"],
    124:["Glasses", "Design 5 (Solar)"],
    125:["Glasses", "Design 5 (Solar over head)"],

    10008:["Pendants", "None"],
    126:["Pendants", "Gold Pendant"],
    127:["Pendants", "Heart Pendant"],
    128:["Pendants", "Bitcoin Pendant"],
    129:["Pendants", "Ethereum Pendant"],
    130:["Pendants", "Solana Pendant"],

    10009:["Piercing","None"],
    131:["Piercing","Nose"],
    132:["Piercing","Lip"],

    10010:["Gadgets", "None"],
    133:["Gadgets", "Airpods (White)"],
    134:["Gadgets", "Airpods (Mate black)"],
    135:["Gadgets", "Hanging on the phone"],

    10011:["On mouth","None"],
    136:["On mouth","Cigarette"],
    137:["On mouth","Marijuana joint"],
    138:["On mouth", "Bubble Gum (Pale rose)"],
    139:["On mouth", "Bubble Gum (Pale blue)"],
    140:["On mouth", "Bubble Gum (Pale green)"],
    141:["On mouth", "Bubble Gum (Pale yellow)"],

    10012:["Mask", "None"],
    142:["Mask", "Surgical mask (White)"],
    143:["Mask", "Surgical mask (Moji Club)"],
}